<a href="https://colab.research.google.com/github/Miltontn7677/Hello_World/blob/master/C1_M5_Fundamental_Case_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Let's test your knowledge about Python, data structures, NumPy, and pandas.
We are going to createa a dummy dataset for some Youtubers regarding their channals. We will create data including:
1.  Decide the size of the dataset by using a SIZE constant variable
1.  ChannelID (`Y0001`, `Y0002`, ...)
1.  Number of subscribers
1.  Number of videos
1.  Number of total views
1.  Category (`['music','news','gaming','food','travel']`)
1.  Language (`['English','Spanish','Japanese','Franch','Russia','Chinese']`)
1.  Type(`['Corperate','Goverment','NGO','Individual']`)


Then we will play with the dummy dataset with our knowledge of pandas, including:
1.  Access
1.  Sampling
1.  Filtering
1.  Aggregation
1.  Manipulation


## Setup environment
Let's import random, Numpy, and pandas

In [1]:
import random
import numpy as np
import pandas as pd

## Dummy dataset generation

### Setup SIZE

In [2]:
# We make this variable SIZE because it supposed to be constant for the runtime.
SIZE = 10000

### Generate ChannelID

In [20]:
ids = ['Y{0:04d}'.format(x) for x in range(SIZE)]
ids[:5], ids[-5:]

(['Y0000', 'Y0001', 'Y0002', 'Y0003', 'Y0004'],
 ['Y9995', 'Y9996', 'Y9997', 'Y9998', 'Y9999'])

### Generate # of subscribers

#### We first simulate a normal distribution

In [21]:
subs = np.random.normal(100000, 50000, (SIZE))
subs[:5], subs[-5:]

(array([ 75545.6520597 , 127614.21512975,  19278.70724125, 174124.57224546,
        160581.72945266]),
 array([ 83353.35680094, 146092.96908105, 165349.31806463,  22142.39211077,
        108485.02570937]))

#### We convert the float numbers to integer

In [22]:
subs = subs.astype(int)
subs[:5], subs[-5:]

(array([ 75545, 127614,  19278, 174124, 160581]),
 array([ 83353, 146092, 165349,  22142, 108485]))

#### We check if there are non-positive numbers of subscribers

In [23]:
subs[subs <= 0 ]

array([ -44104,  -31218,  -17490,  -13328,   -4929,   -1446,   -8775,
        -12403,   -9036,  -16289,   -3783,  -47955,   -5045,  -22073,
         -8553,   -1589,  -53868,   -7535,  -17979,   -1670,   -4375,
        -31838,  -47300,  -11733,  -37041,   -4168,   -7163,  -54113,
         -3330,  -17124,  -26328,  -45013,   -6355,   -2328,  -22204,
        -14356,  -32700,  -12461,  -44969,  -21378,  -27616,   -4919,
        -11000, -100154,  -29830,   -1636,   -4147,  -28135,   -7235,
        -37966,  -39448,  -17846,   -3551,   -9550,   -6815,   -8666,
         -5266,  -15955,  -18923,  -30681,  -27431,   -2880,   -2465,
        -41484,   -4211,   -8222,   -5212,  -11430,  -29234,  -21767,
         -2670,   -1397,  -42468,  -14906,  -37590,  -29914,  -19391,
        -15330,   -5180,  -11382,  -22688,  -17552,  -19730,  -45482,
         -5696,  -19155,  -15970,   -4461,  -21552,  -10130,  -28152,
         -5416,   -5504,  -24076,   -4337,   -2888,  -15578,   -1443,
          -358,   -9

#### We set them to be 1

In [24]:
subs[subs <= 0 ] = 1
subs[subs <= 0 ]

array([], dtype=int64)

### Generate number of videos


#### We use a uniform distribution this time (just for practice)

In [26]:
nvideos = [np.random.randint(1, 100) for i in range(SIZE)]
nvideos[:5], nvideos[-5:]

([59, 78, 54, 44, 24], [51, 76, 61, 13, 90])

### We simulate the number of views

#### To make it real, we will use the # of subscribers and # of videos as factors to get the # of total views

In [27]:
views = [ int(x*1.5*np.random.random() + y*2*np.random.random() + np.random.randint(-1000, 1000))
for x, y in zip(subs, nvideos)]
views[:5], views[-5:]

([58940, 94212, 27289, 16646, 193818], [43278, 119155, 82947, 1307, 158901])

In [28]:
views = np.array(views)
views

array([ 58940,  94212,  27289, ...,  82947,   1307, 158901])

In [29]:
views[views < 0]

array([-673, -729, -343, -172, -504, -399, -186, -740,  -40, -554, -865,
       -446,   -8,  -88, -297, -861, -605, -245, -111, -224, -136, -979,
       -683, -836, -503, -337, -578, -267, -243, -351, -710, -854, -215,
       -174, -425, -234, -219, -520, -722, -591, -429, -172, -987, -110,
       -147, -908, -560,  -70,   -4, -533, -801, -564, -258, -261, -240,
       -175,  -87, -232, -636, -329,  -85, -228, -622, -243, -368, -894,
       -679,  -49, -113, -376, -735, -633, -180, -371, -311, -873, -920,
       -739,  -39, -176, -360, -927, -110, -866, -519, -567,  -78, -404,
       -321, -520, -810, -681, -624, -301, -617, -697, -327, -417, -839,
       -883, -572, -988, -160, -169,  -89, -305, -878, -506, -227, -170,
       -694,  -21, -612, -675, -222,  -85, -426, -455, -691, -549, -419,
        -15, -353, -854, -515, -233, -858, -490, -602, -962])

In [30]:
views[views < 0] = 0
views[views < 0]

array([], dtype=int64)

### Category

>Category (`['music','news','gaming','food','travel']`)

In [13]:
category = np.random.choice(['music','news','gaming','food','travel'], SIZE)
category[:20]

array(['news', 'travel', 'travel', 'music', 'travel', 'music', 'food',
       'gaming', 'gaming', 'news', 'news', 'travel', 'travel', 'travel',
       'music', 'music', 'music', 'gaming', 'travel', 'food'], dtype='<U6')

### Language
>Language (`['English','Spanish','Japanese','Franch','Russia','Chinese']`)


In [14]:
language = np.random.choice(['English','Spanish','Japanese','Franch','Russia','Chinese'],
                            SIZE, p=[0.5, 0.1, 0.1, 0.1, 0.1, 0.1])
language[:20]

array(['English', 'English', 'Russia', 'English', 'Japanese', 'English',
       'English', 'Chinese', 'English', 'English', 'Russia', 'Chinese',
       'English', 'English', 'Chinese', 'Japanese', 'Spanish', 'Franch',
       'Franch', 'Japanese'], dtype='<U8')

### Type
>Type(`['Corperate','Goverment','NGO','Individual']`)

In [15]:
tp = np.random.choice(['Corperate','Goverment','NGO','Individual'], SIZE, p=[0.1, 0.2, 0.3, 0.4])
tp[:20]

array(['NGO', 'Individual', 'NGO', 'Individual', 'NGO', 'Individual',
       'NGO', 'Individual', 'Individual', 'Individual', 'Corperate',
       'Individual', 'NGO', 'Individual', 'Corperate', 'NGO', 'NGO',
       'Individual', 'Individual', 'Individual'], dtype='<U10')

### Now we have all attributes, let's put them into a dataframe

In [16]:
df = pd.DataFrame({'ChannelID': ids,
                   'subs': subs,
                   'nvideos': nvideos,
                   'views': views,
                   'Category': category,
                   'Language':language,
                   'Type': tp},
                  index = ids)
df.head()

ChannelID    subs  nvideos   views Category  Language        Type
Y0000     Y0000  119614       21    5478     news   English         NGO
Y0001     Y0001  129362       56  142368   travel   English  Individual
Y0002     Y0002   77944       78   13919   travel    Russia         NGO
Y0003     Y0003  101968       88   17531    music   English  Individual
Y0004     Y0004   89937       27   49417   travel  Japanese         NGO

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, Y0000 to Y9999
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ChannelID  10000 non-null  object
 1   subs       10000 non-null  int64 
 2   nvideos    10000 non-null  int64 
 3   views      10000 non-null  int64 
 4   Category   10000 non-null  object
 5   Language   10000 non-null  object
 6   Type       10000 non-null  object
dtypes: int64(3), object(4)
memory usage: 625.0+ KB


### Let's save the dummy dataset to `youtube_channels.csv`

In [18]:
df.to_csv('/content/youtube_channels.csv', index=False)

## Let's play with the dataframe a little bit

### Sampling

#### Select certain rows

In [ ]:
df_sub1 = df.loc[:'Y0100']
df_sub1

ChannelID    subs  nvideos   views Category Language        Type
Y0000     Y0000   28045       61   34515     food   Russia  Individual
Y0001     Y0001  112407        8  137830     food  English   Goverment
Y0002     Y0002   75610       89   75561     food   Franch   Goverment
Y0003     Y0003   68566       17   14567     food  English  Individual
Y0004     Y0004  154427       92  172224   gaming  English         NGO
...         ...     ...      ...     ...      ...      ...         ...
Y0096     Y0096   72594       18    8188     news   Franch  Individual
Y0097     Y0097  125410       90  152805   travel  English  Individual
Y0098     Y0098  137602       73     676    music  English  Individual
Y0099     Y0099  119988       34   52080     news  English         NGO
Y0100     Y0100  105222       19   69281   gaming  English  Individual

[101 rows x 7 columns]

#### Select certain rows and columns

In [ ]:
df_sub2 = df.loc[:'Y1000', ['subs','views']]
df_sub2

subs   views
Y0000   28045   34515
Y0001  112407  137830
Y0002   75610   75561
Y0003   68566   14567
Y0004  154427  172224
...       ...     ...
Y0996   35571   51580
Y0997  102212   95143
Y0998   49603   63737
Y0999    8028    2545
Y1000  131758  106912

[1001 rows x 2 columns]

#### Select randome rows

In [ ]:
df_sub3 = df.iloc[random.sample(range(0, SIZE), 100)]
df_sub3

ChannelID    subs  nvideos   views Category  Language        Type
Y7934     Y7934       1       58     479     news   English         NGO
Y4974     Y4974   48515       47   25066     food    Russia         NGO
Y8898     Y8898   99912       73    1385     food    Russia  Individual
Y1580     Y1580   37341       13   34180   gaming   Chinese   Goverment
Y4149     Y4149  173878       19  226348    music  Japanese         NGO
...         ...     ...      ...     ...      ...       ...         ...
Y8747     Y8747  101132       80  150711     news    Russia  Individual
Y6329     Y6329  114735       80  170020     food   English  Individual
Y0242     Y0242  178802       55  220842     news    Russia  Individual
Y2615     Y2615  219678        1  254137    music   English   Corperate
Y2270     Y2270   84831       39  102813    music   English  Individual

[100 rows x 7 columns]

#### Select random rows with selected columns

In [ ]:
df_sub4 = df.iloc[random.sample(range(0, SIZE), 100)][['subs','views']]
df_sub4

subs   views
Y7633   79223   40161
Y7965   77167   40551
Y4786   28367   35095
Y1991  179690  176777
Y1831   41955    4277
...       ...     ...
Y8427   93260    4679
Y6860  185962  266192
Y1589  166517   67476
Y3098   64708    2307
Y4297   90637   55938

[100 rows x 2 columns]

### Filtering

#### Super Popular Channel

In [ ]:
df_superp = df[df['subs'] > 300000]
df_superp

Empty DataFrame
Columns: [ChannelID, subs, nvideos, views, Category, Language, Type]
Index: []

#### Popular Channel

In [ ]:
df_p = df[df['subs'] > 100000]
df_p

ChannelID    subs  nvideos   views Category  Language        Type
Y0001     Y0001  112407        8  137830     food   English   Goverment
Y0004     Y0004  154427       92  172224   gaming   English         NGO
Y0005     Y0005  171466       61  183685     food   English  Individual
Y0008     Y0008  142673       87  154982     food   English   Corperate
Y0013     Y0013  112532       20   74012   gaming   English   Goverment
...         ...     ...      ...     ...      ...       ...         ...
Y9993     Y9993  149002        3  140254   gaming  Japanese   Goverment
Y9994     Y9994  100716       70   90956     news  Japanese         NGO
Y9995     Y9995  119716       68    5922     food   English   Goverment
Y9996     Y9996  111044       19   58326    music    Franch  Individual
Y9998     Y9998  233726       11   78299   gaming   English         NGO

[4954 rows x 7 columns]

#### Start up channel

In [ ]:
df_begin = df[df['subs'] < 100]
df_begin

ChannelID  subs  nvideos  views Category Language        Type
Y0123     Y0123     1       40      0   gaming  English  Individual
Y0189     Y0189     1       17      0    music  English  Individual
Y0198     Y0198     1       47    826     news   Russia   Goverment
Y0221     Y0221     1       45      0   travel  English         NGO
Y0248     Y0248     1       83    885   travel  English  Individual
...         ...   ...      ...    ...      ...      ...         ...
Y9769     Y9769     1       42      0   gaming  English   Goverment
Y9791     Y9791     1       64    199   travel  English  Individual
Y9864     Y9864     1       14     54    music  English   Corperate
Y9901     Y9901     1       77      0    music  English         NGO
Y9944     Y9944     1        7      0   travel  Spanish  Individual

[260 rows x 7 columns]

#### Popular English Channel

In [ ]:
df_EnglishP = df[(df['subs'] > 100000) & (df['Language'] == 'English')]
df_EnglishP

ChannelID    subs  nvideos   views Category Language        Type
Y0001     Y0001  112407        8  137830     food  English   Goverment
Y0004     Y0004  154427       92  172224   gaming  English         NGO
Y0005     Y0005  171466       61  183685     food  English  Individual
Y0008     Y0008  142673       87  154982     food  English   Corperate
Y0013     Y0013  112532       20   74012   gaming  English   Goverment
...         ...     ...      ...     ...      ...      ...         ...
Y9979     Y9979  135756       35   83628   gaming  English         NGO
Y9984     Y9984  152586       41    8405   travel  English         NGO
Y9985     Y9985  115796        8  146382    music  English  Individual
Y9995     Y9995  119716       68    5922     food  English   Goverment
Y9998     Y9998  233726       11   78299   gaming  English         NGO

[2508 rows x 7 columns]

#### Gaming channel with many videos

In [42]:
df_gaming_nv = df[(df['Category'] == 'gaming') & (df['nvideos'] > 90)]
df_gaming_nv

ChannelID    subs  nvideos   views Category  Language        Type
Y0079     Y0079   59263       99   85450   gaming  Japanese  Individual
Y0090     Y0090  142168       96  199881   gaming  Japanese  Individual
Y0209     Y0209  110275       98   35450   gaming   English   Goverment
Y0255     Y0255   59963       99   13030   gaming   English         NGO
Y0289     Y0289  121072       92   63713   gaming   English  Individual
...         ...     ...      ...     ...      ...       ...         ...
Y9843     Y9843   99041       94   38353   gaming   English   Corperate
Y9868     Y9868   94619       93   71531   gaming   English  Individual
Y9892     Y9892   91300       97  115850   gaming   Spanish   Goverment
Y9910     Y9910  210919       95    4510   gaming   Spanish  Individual
Y9935     Y9935  126409       99  103104   gaming    Russia         NGO

[170 rows x 7 columns]

#### Non-Corperate and News channel

In [41]:
df_nc_news = df[(df['Category'] == 'news') & (df['Type'] != 'Corperate')]
df_nc_news

ChannelID    subs  nvideos   views Category  Language        Type
Y0000     Y0000  119614       21    5478     news   English         NGO
Y0009     Y0009  179155       52  143468     news   English  Individual
Y0021     Y0021  190699       34   22892     news   English         NGO
Y0028     Y0028  153022       50   31232     news   English         NGO
Y0030     Y0030  170645       30  115108     news  Japanese         NGO
...         ...     ...      ...     ...      ...       ...         ...
Y9989     Y9989  110032       83   18983     news   Spanish  Individual
Y9993     Y9993  116442        4  164016     news  Japanese         NGO
Y9994     Y9994  195075       83  136657     news   English         NGO
Y9996     Y9996   49098        4   36844     news   Spanish  Individual
Y9997     Y9997   54334        9    7820     news   English  Individual

[1902 rows x 7 columns]

#### Top Subs **and** Top nvideos

In [ ]:
df_subs_and_nvideos = df[(df['subs'] > 200000) & (df['nvideos'] > 90)]
df_subs_and_nvideos

ChannelID    subs  nvideos   views Category  Language        Type
Y0457     Y0457  200578       98  179438    music   English         NGO
Y1234     Y1234  270322       91  246792    music   English  Individual
Y1752     Y1752  252441       97   94488    music   Spanish         NGO
Y1966     Y1966  239748       95  234882   gaming   English   Goverment
Y2118     Y2118  203434       94  251128   gaming    Russia   Goverment
Y2264     Y2264  209237       99  214449     news   English  Individual
Y2369     Y2369  215407       91  222893   travel   English  Individual
Y2655     Y2655  216743       98  294638   gaming   Chinese         NGO
Y2788     Y2788  253750       95   41430     food    Russia  Individual
Y3241     Y3241  204562       91   36758   travel   English         NGO
Y3638     Y3638  203695       92  105152   travel   English  Individual
Y4299     Y4299  206313       92  262688     food    Franch         NGO
Y4448     Y4448  209516       99   86288   travel   Chinese  Individual
Y4864     Y4864  204706       99  196701   gaming    Franch         NGO
Y5119     Y5119  206155       97  277033     food  Japanese         NGO
Y5522     Y5522  207977       96  272143    music   English   Goverment
Y5687     Y5687  212592       94  195757    music    Franch         NGO
Y6402     Y6402  222586       98  253222     news  Japanese   Corperate
Y6499     Y6499  210285       92  239858   gaming   English  Individual
Y6777     Y6777  251861       91  243649    music    Franch  Individual
Y7162     Y7162  206708       91  221836    music   English  Individual
Y7860     Y7860  234626       92  229870   travel   English         NGO
Y8038     Y8038  200119       92   28748   travel   English   Corperate
Y8525     Y8525  244921       97  359679     food   English  Individual
Y8773     Y8773  213818       97  224340     news   English         NGO

#### Top Subs **or** Top nvideos

In [48]:
df_subs_or_nvideos = df[(df['subs'] > 200000) | (df['nvideos'] > 90)][['subs','nvideos', 'views']]
df_subs_or_nvideos

subs  nvideos   views
Y0016  170698       93  163652
Y0024   66676       99   40549
Y0035   32444       97   34680
Y0038  152161       98   56780
Y0039  234720       29   43430
...       ...      ...     ...
Y9937  143588       95  157549
Y9943    2734       97       0
Y9969  187498       99  139353
Y9971   91152       95   66549
Y9998   80186       98   31947

[1118 rows x 3 columns]

### Aggregation

In [49]:
byCategory = df.groupby('Category')[['subs','nvideos', 'views']]
byCategory.sum()

subs  nvideos      views
Category                               
food      194925856    96851  144560057
gaming    192999197    97553  144061987
music     205136598   101092  153640094
news      206036518   104408  150964874
travel    199034181   100988  151842917

In [50]:
byCategory.mean()

subs    nvideos         views
Category                                        
food      101260.184935  50.312208  75096.133506
gaming     98619.926929  49.848237  73613.687787
music     101703.816559  50.119980  76172.580069
news       98865.891555  50.099808  72439.958733
travel     98678.324740  50.068418  75281.565196

In [51]:
byLanguage = df.groupby('Language')[['subs','nvideos', 'views']]
byLanguage.sum()

subs  nvideos      views
Language                               
Chinese   102866916    52258   77050650
English   502442920   251692  373323758
Franch    103529170    52751   76865323
Japanese  100132200    49432   76553038
Russia     93317565    46055   69461441
Spanish    95843579    48704   71815719

In [52]:
byLanguage.mean()

subs    nvideos         views
Language                                        
Chinese    99773.924345  50.686712  74733.899127
English    99928.981702  50.058075  74248.957438
Franch     98599.209524  50.239048  73205.069524
Japanese  101760.365854  50.235772  77797.802846
Russia     99698.253205  49.204060  74210.941239
Spanish    98706.054583  50.158599  73960.575695

In [31]:
byLanType = df.groupby(['Language', 'Type'])
byLanType.describe()

subs                                              \
                      count           mean           std  min       25%   
Language Type                                                             
Chinese  Corperate    107.0   94470.093458  44814.375270  1.0  73118.00   
         Goverment    197.0   99275.868020  50173.351328  1.0  60392.00   
         Individual   411.0  100880.469586  51995.042218  1.0  64757.50   
         NGO          316.0  100441.129747  49051.336178  1.0  64849.25   
English  Corperate    492.0  100388.536585  49232.185345  1.0  66840.50   
         Goverment   1035.0  100808.925604  50572.258532  1.0  64121.00   
         Individual  2018.0   99255.201685  48506.709107  1.0  65558.75   
         NGO         1483.0  100079.248146  50039.896487  1.0  65347.00   
Franch   Corperate    103.0  103820.398058  45288.632909  1.0  73929.00   
         Goverment    209.0   98566.397129  52524.928647  1.0  62963.00   
         Individual   433.0   96112.314088  48778.602599  1.0  61007.00   
         NGO          305.0  100389.049180  48389.640833  1.0  63958.00   
Japanese Corperate     85.0   88897.964706  51669.550243  1.0  56213.00   
         Goverment    217.0  105870.585253  50796.627536  1.0  71998.00   
         Individual   390.0  104165.687179  51034.412184  1.0  66406.50   
         NGO          292.0   99237.458904  52464.611590  1.0  64441.75   
Russia   Corperate     89.0   95054.044944  44840.444908  1.0  65723.00   
         Goverment    182.0   97337.802198  45454.057345  1.0  64634.00   
         Individual   360.0  101741.886111  50101.905092  1.0  65971.25   
         NGO          305.0  100049.822951  45491.798039  1.0  69360.00   
Spanish  Corperate     99.0   97077.585859  49503.356995  1.0  61701.50   
         Goverment    178.0   98426.477528  51395.054119  1.0  60246.75   
         Individual   412.0   99011.825243  51285.367657  1.0  61535.50   
         NGO          282.0   99007.492908  50120.325706  1.0  61480.25   

                                                   nvideos             ...  \
                          50%        75%       max   count       mean  ...   
Language Type                                                          ...   
Chinese  Corperate    96739.0  123541.00  202700.0   107.0  51.672897  ...   
         Goverment    98591.0  132409.00  233678.0   197.0  52.502538  ...   
         Individual   98043.0  136746.00  296206.0   411.0  51.454988  ...   
         NGO          94240.5  136937.00  240623.0   316.0  48.221519  ...   
English  Corperate   100430.5  135314.25  227192.0   492.0  49.674797  ...   
         Goverment    99939.0  138127.00  254055.0  1035.0  50.225121  ...   
         Individual   98817.0  132691.75  266870.0  2018.0  49.750743  ...   
         NGO         100260.0  133010.00  269019.0  1483.0  50.486851  ...   
Franch   Corperate   106741.0  133611.00  202997.0   103.0  55.553398  ...   
         Goverment   100986.0  133174.00  216027.0   209.0  47.550239  ...   
         Individual   94110.0  128419.00  248839.0   433.0  51.836028  ...   
         NGO         103666.0  135900.00  213854.0   305.0  48.019672  ...   
Japanese Corperate    87289.0  121453.00  205990.0    85.0  53.858824  ...   
         Goverment   104558.0  138233.00  222686.0   217.0  52.188940  ...   
         Individual  103971.5  141956.75  296692.0   390.0  49.115385  ...   
         NGO          99085.5  134506.25  235016.0   292.0  49.226027  ...   
Russia   Corperate    98106.0  116974.00  245811.0    89.0  49.000000  ...   
         Goverment    96385.5  127462.50  227234.0   182.0  49.956044  ...   
         Individual  103729.5  139681.50  266343.0   360.0  48.861111  ...   
         NGO          99081.0  131397.00  210201.0   305.0  49.219672  ...   
Spanish  Corperate    96363.0  135493.50  246659.0    99.0  46.767677  ...   
         Goverment    96748.0  133575.25  248760.0   178.0  54.971910  ...   
         Individual   98120.0  138385.75  29407

In [ ]:
byLanType.describe()[['subs','views']]

subs                                              \
                      count           mean           std  min       25%   
Language Type                                                             
Chinese  Corperate    110.0   99457.336364  50733.441208  1.0  62248.00   
         Goverment    237.0  102804.552743  52212.092706  1.0  70381.00   
         Individual   406.0   95629.667488  50165.313076  1.0  58861.00   
         NGO          292.0  103402.729452  51112.394733  1.0  69207.50   
English  Corperate    509.0   96385.499018  51289.569872  1.0  59867.00   
         Goverment    942.0  100659.650743  48636.473989  1.0  66303.00   
         Individual  2042.0   99512.581293  49236.312216  1.0  66363.00   
         NGO         1488.0  100473.995968  49121.816322  1.0  66272.75   
Franch   Corperate    115.0   95224.339130  47015.224298  1.0  63358.50   
         Goverment    184.0  106364.016304  49287.658376  1.0  68470.25   
         Individual   402.0  102360.087065  48107.306405  1.0  69731.00   
         NGO          297.0   99150.471380  49538.230429  1.0  61748.00   
Japanese Corperate     99.0  107543.101010  48240.195506  1.0  70032.00   
         Goverment    213.0   99929.657277  45414.076484  1.0  70109.00   
         Individual   437.0  100754.350114  46178.322297  1.0  67055.00   
         NGO          297.0  101533.680135  50876.264972  1.0  65658.00   
Russia   Corperate     78.0   97518.435897  42844.391905  1.0  68983.75   
         Goverment    189.0  100941.333333  49441.830860  1.0  70928.00   
         Individual   378.0   96058.542328  48338.538666  1.0  61912.00   
         NGO          309.0   96562.779935  49256.079654  1.0  63280.00   
Spanish  Corperate     93.0   92909.806452  46227.832268  1.0  64779.00   
         Goverment    188.0  101609.914894  47198.701891  1.0  64861.75   
         Individual   399.0  100184.558897  49745.512587  1.0  66689.50   
         NGO          296.0   96523.175676  49759.531255  1.0  61615.50   

                                                     views                \
                          50%        75%       max   count          mean   
Language Type                                                              
Chinese  Corperate    98675.5  135087.50  237038.0   110.0  71285.681818   
         Goverment   100310.0  134932.00  263176.0   237.0  74188.147679   
         Individual   96165.5  132292.75  247324.0   406.0  75170.899015   
         NGO         101904.5  135814.75  261685.0   292.0  80094.486301   
English  Corperate    94118.0  130254.00  286875.0   509.0  71423.113949   
         Goverment   102239.0  135400.00  239748.0   942.0  75625.174098   
         Individual  100693.0  132786.75  282862.0  2042.0  75803.887855   
         NGO         100893.0  132323.75  260881.0  1488.0  76675.464382   
Franch   Corperate    93194.0  128991.00  255294.0   115.0  68803.686957   
         Goverment   105015.0  143614.25  224179.0   184.0  78024.032609   
         Individual   99148.5  136601.75  251861.0   402.0  76677.910448   
         NGO          98632.0  134409.00  251957.0   297.0  77877.016835   
Japanese Corperate   101998.0  142026.00  222586.0    99.0  87365.040404   
         Goverment   100804.0  131386.00  215839.0   213.0  83696.690141   
         Individual   98685.0  132725.00  245272.0   437.0  80041.700229   
         NGO          99841.0  137068.00  234421.0   297.0  73458.612795   
Russia   Corperate    92531.5  125842.50  198685.0    78.0  71480.782051   
         Goverment    99725.0  131467.00  235418.0   189.0  83587.021164   
         Individual   95125.0  131080.50  253750.0   378.0  74863.158730   
         NGO          98793.0  128026.00  247106.0   309.0  72970.556634   
Spanish  Corperate    92387.0  117625.00  224218.0    93.0  67612.064516   
         Goverment   102255.0  139183.75  199215.0   188.0  74287.627660   
         Individual  100733.0  136009.50  235658.0   399.0  72243.556391   
         NGO         

In [ ]:
byLanType.describe().loc['English',['subs','views']]

subs                                                        \
             count           mean           std  min       25%       50%   
Type                                                                       
Corperate    509.0   96385.499018  51289.569872  1.0  59867.00   94118.0   
Goverment    942.0  100659.650743  48636.473989  1.0  66303.00  102239.0   
Individual  2042.0   99512.581293  49236.312216  1.0  66363.00  100693.0   
NGO         1488.0  100473.995968  49121.816322  1.0  66272.75  100893.0   

                                  views                                   \
                  75%       max   count          mean           std  min   
Type                                                                       
Corperate   130254.00  286875.0   509.0  71423.113949  60978.184166  0.0   
Goverment   135400.00  239748.0   942.0  75625.174098  60702.564724  0.0   
Individual  132786.75  282862.0  2042.0  75803.887855  61317.297230  0.0   
NGO         132323.75  260881.0  1488.0  76675.464382  60287.765229  0.0   

                                                    
                 25%      50%        75%       max  
Type                                                
Corperate   23229.00  57982.0  102267.00  303855.0  
Goverment   26101.50  62926.5  112054.25  311153.0  
Individual  25055.75  64702.5  113763.50  359679.0  
NGO         27884.50  62826.5  113427.50  329993.0

### Manipulation

In [45]:
df['subpervideo'] = df['subs']/df['nvideos']
df['subpervideo'].describe()

count     10000.000000
mean       5210.394593
std       13310.379410
min           0.010101
25%        1155.393981
50%        2005.504098
75%        3955.726935
max      199634.000000
Name: subpervideo, dtype: float64

In [46]:
df['viewspervideo'] = df['views']/df['nvideos']
df['viewspervideo'].describe()

count     10000.000000
mean       3854.294507
std       11529.066170
min           0.000000
25%         502.321678
50%        1329.734506
75%        2982.351599
max      233281.000000
Name: viewspervideo, dtype: float64

In [ ]:
df['viewspersub'] = df['views']/df['subs']
df['viewspersub'].describe()

count    10000.000000
mean         8.448969
std         73.398496
min          0.000000
25%          0.376409
50%          0.766664
75%          1.140467
max       1134.000000
Name: viewspersub, dtype: float64

In [ ]:
df.head(10)

ChannelID    subs  nvideos   views Category Language        Type  \
Y0000     Y0000   28045       61   34515     food   Russia  Individual   
Y0001     Y0001  112407        8  137830     food  English   Goverment   
Y0002     Y0002   75610       89   75561     food   Franch   Goverment   
Y0003     Y0003   68566       17   14567     food  English  Individual   
Y0004     Y0004  154427       92  172224   gaming  English         NGO   
Y0005     Y0005  171466       61  183685     food  English  Individual   
Y0006     Y0006   25407       30   29163     news  English         NGO   
Y0007     Y0007   90808       74  133107     food   Franch   Goverment   
Y0008     Y0008  142673       87  154982     food  English   Corperate   
Y0009     Y0009   42078       66   42632     news  English  Individual   

        subpervideo  viewspervideo  viewspersub  
Y0000    459.754098     565.819672     1.230701  
Y0001  14050.875000   17228.750000     1.226169  
Y0002    849.550562     849.000000     0.999352  
Y0003   4033.294118     856.882353     0.212452  
Y0004   1678.554348    1872.000000     1.115245  
Y0005   2810.918033    3011.229508     1.071262  
Y0006    846.900000     972.100000     1.147833  
Y0007   1227.135135    1798.743243     1.465807  
Y0008   1639.919540    1781.402299     1.086274  
Y0009    637.545455     645.939394     1.013166

## Congratulations! You completed our course: Data Wrangling -- Fundamentals